### ISSUE TITLE
Some PDFs and their relative ePub are corrupted.

### ISSUE THREAD

**Issue by Dr4w** [emmaKts/springer-nature-free-english-textbooks#1]
Some PDF and (if they exist) their relative ePubs are corrupted and are not downloaded properly (empty file with no extension).
They're not a lot and can be easily downloaded manually, but if you're interested in trying to fix the issue I'll leave some example.
-Behavioral Science: Clinical Neuroanatomy.
-Biomedical and Life Sciences: ENZEMYS, Epidemiological Research.
There are a few other folders affected. If needed I can provide you all the names of the affected files.
I'm running the script on a Windows 10 machine and NOT in a virtual python machine.

**Comment by emmaKts** [comment]
Thanks for the issue, I was discussing exactly the same thing in another issue created in a similar repo. I am going to try and fix it, I believe it has to do with the fact that some of the files are quite big - it'd be great if you could confirm that btw.

**Comment by emmaKts** [comment]
Thanks for the issue @Dr4w, I was discussing exactly the same thing in another issue created in a similar repo. I am going to try and fix it, I believe it has to do with the fact that some of the files are quite big - it'd be great if you could confirm that btw.

**Comment by emmaKts** [comment]
Thanks for the issue @Dr4w, I was discussing something like this in a similar repo. 

- Tried to reproduce it on my (macOS) machine and it seems to be downloading them fine.
- Managed to reproduce it on a Windows machine and I believe that the problem is the ":" in the titles of those textbooks. 

Could you please confirm that all of the corrupted files have a colon in their titles?

**Comment by Dr4w** [comment]
@emmaKts Yes, I can confirm that all the corrupted files contains ":" in their names. I can't see your other comment regarding the size of the files, but anyway, I don't think it's related to that, since some corrupted files are the same size or even smaller than the non-corrupted ones.

**Comment by emmaKts** [comment]
@Dr4w Thanks, I am going to merge to master. Feel free to try out if you'd like to.

**Comment by Dr4w** [comment]
The issue is fixed. Tho, I tried counting all the PDF files (through a powershell script) and the result was 393 while they should be 407 (according to the excel file). I have no idea on how to check which files are missing, but I would appreciate if you could give it a look.
